### ISSUE TITLE
Issue with print function

### ISSUE THREAD

**Issue by EvanWieland** [quantumsheep/demo-antlr4-llvm#1]
First of all - awesome project!

I've been playing with your demo and have been having issues with the `print` function. When I attempt to use it I get this error:

```
JIT session error: Symbols not found: [ printf ]
Failed to materialize symbols: { (main, { main }) }
```

Everything else seems to work great. Any ideas what might be going on? Thanks!

**Comment by EvanWieland** [comment]
#2 
This PR attempts to correct the issue.

**Comment by quantumsheep** [comment]
I'm surprised that the linker didn't handle printf by itself. Thanks for the PR!
